name: CI

on:
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - $${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1.2']
        os: [ubuntu-latest, macOS-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia-actions/julia-runtest@latest
